### ISSUE TITLE
[Task] 좋아요 기능 구현

### ISSUE THREAD

**Issue by tmddl0807** [codestates/aneun-dongne#10]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 좋아요 추가 및 삭제 로직을 구현

### TODO
1. [ ] 좋아요 기능 구현
2. [ ] 좋아요 개수 조회
3. [ ] 유저가 좋아요를 한번 클릭할 때마다 추가 및 삭제가 가능하게 하기

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint : `Sprint__1__`
- Urgency : `High`
